require('dotenv').config();

module.exports = {
  port: process.env.PORT || 5000,
  databaseUrl: process.env.DATABASE_URL,
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET,
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET,
  adminEmail: process.env.ADMIN_EMAIL,
  adminPassword: process.env.ADMIN_PASSWORD,
  clientUrl: process.env.CLIENT_URL,
  clientUrls: process.env.CLIENT_URLS,
  nodeEnv: process.env.NODE_ENV,
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME,
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY,
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET,
  cloudinaryUrl: process.env.CLOUDINARY_URL,
  emailjsOtpServiceId: process.env.EMAILJS_OTP_SERVICE_ID,
  emailjsOtpTemplateId: process.env.EMAILJS_OTP_TEMPLATE_ID,
  emailjsOtpPublicKey: process.env.EMAILJS_OTP_PUBLIC_KEY,
  emailjsOtpPrivateKey: process.env.EMAILJS_OTP_PRIVATE_KEY,
  emailjsWelcomeServiceId: process.env.EMAILJS_WELCOME_SERVICE_ID,
  emailjsWelcomeTemplateId: process.env.EMAILJS_WELCOME_TEMPLATE_ID,
  emailjsWelcomePublicKey: process.env.EMAILJS_WELCOME_PUBLIC_KEY,
  emailjsWelcomePrivateKey: process.env.EMAILJS_WELCOME_PRIVATE_KEY,
  googleWebClientId: process.env.GOOGLE_WEB_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  firebaseServiceAccount: process.env.FIREBASE_SERVICE_ACCOUNT,
};
